// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBHLkZI8dr_yAkTsMHAxIAq2tyb9CpFcsk',
    appId: '1:775387053443:web:d3250c7263097e352e0ab6',
    messagingSenderId: '775387053443',
    projectId: 'scissors-834da',
    authDomain: 'scissors-834da.firebaseapp.com',
    storageBucket: 'scissors-834da.appspot.com',
    measurementId: 'G-37KH91R4E6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvu6HymBsvy1hBd0_6b7KMnGhyxDvUwO0',
    appId: '1:775387053443:android:ac930860141ee9382e0ab6',
    messagingSenderId: '775387053443',
    projectId: 'scissors-834da',
    storageBucket: 'scissors-834da.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLytmT7xd-5B8A3z72zDLQZteQ4C4ynWE',
    appId: '1:775387053443:ios:6bb7568f8f9a6af32e0ab6',
    messagingSenderId: '775387053443',
    projectId: 'scissors-834da',
    storageBucket: 'scissors-834da.appspot.com',
    iosBundleId: 'com.example.scissorsSalonProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLytmT7xd-5B8A3z72zDLQZteQ4C4ynWE',
    appId: '1:775387053443:ios:71456944d69623ef2e0ab6',
    messagingSenderId: '775387053443',
    projectId: 'scissors-834da',
    storageBucket: 'scissors-834da.appspot.com',
    iosBundleId: 'com.example.scissorsSalonProject.RunnerTests',
  );
}
